services:
  backend:
    image: wenbushi/ngx_http_proxy_connect
    ports:
    - "3128:3128"
    volumes:
    - ./conf.d:/etc/nginx/conf.d:ro
    - ./nginx.conf:/etc/nginx/nginx.conf
    # htpasswd -c conf.d/htpasswd username
