services:
  backend:
    build: .
    ports:
    - "3128:3128"
    # - "80:80"
    volumes:
    - ./conf.d:/etc/nginx/conf.d:ro
    # - ./nginx.conf:/etc/nginx/nginx.conf
    # htpasswd -c conf.d/htpasswd username
